apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "cairn.fullname" . }}-cairn-injected-pods
  labels:
  {{- include "cairn.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /metrics
    port: cairn-metrics
    scheme: http
  selector:
    matchLabels:
      cairn.io/agent-injected: "true"
