apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cairn.fullname" . }}-clusterrightsizepolicy-viewer-role
  labels:
  {{- include "cairn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - clusterrightsizepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - clusterrightsizepolicies/status
  verbs:
  - get
