apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cairn.fullname" . }}-rightsizerecommendation-editor-role
  labels:
  {{- include "cairn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizerecommendations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizerecommendations/status
  verbs:
  - get
