apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cairn.fullname" . }}-rightsizepolicy-admin-role
  labels:
  {{- include "cairn.labels" . | nindent 4 }}
rules:
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizepolicies
  verbs:
  - '*'
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizepolicies/status
  verbs:
  - get
