apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "cairn.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "cairn.fullname" . }}-serving-cert
  labels:
  {{- include "cairn.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "cairn.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-rightsizing-cairn-io-v1alpha1-clusterrightsizepolicy
  failurePolicy: Fail
  name: vclusterrightsizepolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.cairn.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusterrightsizepolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "cairn.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-rightsizing-cairn-io-v1alpha1-rightsizepolicy
  failurePolicy: Fail
  name: vrightsizepolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rightsizing.cairn.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rightsizepolicies
  sideEffects: None
