# This rule is not used by the project cairn itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to rightsizing.cairn.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cairn
    app.kubernetes.io/managed-by: kustomize
  name: rightsizerecommendation-viewer-role
rules:
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizerecommendations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizerecommendations/status
  verbs:
  - get
