---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - clusterrightsizepolicies
  - rightsizepolicies
  - rightsizerecommendations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - clusterrightsizepolicies/finalizers
  - rightsizepolicies/finalizers
  - rightsizerecommendations/finalizers
  verbs:
  - update
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - clusterrightsizepolicies/status
  - rightsizepolicies/status
  - rightsizerecommendations/status
  verbs:
  - get
  - patch
  - update
