---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizepolicies
  - rightsizerecommendations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizepolicies/finalizers
  - rightsizerecommendations/finalizers
  verbs:
  - update
- apiGroups:
  - rightsizing.cairn.io
  resources:
  - rightsizepolicies/status
  - rightsizerecommendations/status
  verbs:
  - get
  - patch
  - update
