//go:build !ignore_autogenerated

/*
Copyright 2026 The Cairn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BurstState) DeepCopyInto(out *BurstState) {
	*out = *in
	if in.BurstPeakCPU != nil {
		in, out := &in.BurstPeakCPU, &out.BurstPeakCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.BurstPeakMemory != nil {
		in, out := &in.BurstPeakMemory, &out.BurstPeakMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.BurstStartTime != nil {
		in, out := &in.BurstStartTime, &out.BurstStartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BurstState.
func (in *BurstState) DeepCopy() *BurstState {
	if in == nil {
		return nil
	}
	out := new(BurstState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRightsizePolicy) DeepCopyInto(out *ClusterRightsizePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRightsizePolicy.
func (in *ClusterRightsizePolicy) DeepCopy() *ClusterRightsizePolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterRightsizePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRightsizePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRightsizePolicyList) DeepCopyInto(out *ClusterRightsizePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterRightsizePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRightsizePolicyList.
func (in *ClusterRightsizePolicyList) DeepCopy() *ClusterRightsizePolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterRightsizePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterRightsizePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRightsizePolicySpec) DeepCopyInto(out *ClusterRightsizePolicySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(NamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
	in.CommonPolicySpec.DeepCopyInto(&out.CommonPolicySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRightsizePolicySpec.
func (in *ClusterRightsizePolicySpec) DeepCopy() *ClusterRightsizePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterRightsizePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRightsizePolicyStatus) DeepCopyInto(out *ClusterRightsizePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRightsizePolicyStatus.
func (in *ClusterRightsizePolicyStatus) DeepCopy() *ClusterRightsizePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterRightsizePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonPolicySpec) DeepCopyInto(out *CommonPolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = new(ContainerPolicies)
		(*in).DeepCopyInto(*out)
	}
	if in.Java != nil {
		in, out := &in.Java, &out.Java
		*out = new(JavaPolicy)
		(*in).DeepCopyInto(*out)
	}
	out.Window = in.Window
	out.MinApplyInterval = in.MinApplyInterval
	out.MinObservationWindow = in.MinObservationWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonPolicySpec.
func (in *CommonPolicySpec) DeepCopy() *CommonPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CommonPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerPolicies) DeepCopyInto(out *ContainerPolicies) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(ContainerResourcePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(ContainerResourcePolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerPolicies.
func (in *ContainerPolicies) DeepCopy() *ContainerPolicies {
	if in == nil {
		return nil
	}
	out := new(ContainerPolicies)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRecommendation) DeepCopyInto(out *ContainerRecommendation) {
	*out = *in
	in.Current.DeepCopyInto(&out.Current)
	if in.Recommended != nil {
		in, out := &in.Recommended, &out.Recommended
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.LowerBound != nil {
		in, out := &in.LowerBound, &out.LowerBound
		*out = new(ResourceValues)
		(*in).DeepCopyInto(*out)
	}
	if in.UpperBound != nil {
		in, out := &in.UpperBound, &out.UpperBound
		*out = new(ResourceValues)
		(*in).DeepCopyInto(*out)
	}
	if in.JVM != nil {
		in, out := &in.JVM, &out.JVM
		*out = new(JVMRecommendation)
		(*in).DeepCopyInto(*out)
	}
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(BurstState)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRecommendation.
func (in *ContainerRecommendation) DeepCopy() *ContainerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourcePolicy) DeepCopyInto(out *ContainerResourcePolicy) {
	*out = *in
	if in.MinRequest != nil {
		in, out := &in.MinRequest, &out.MinRequest
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxRequest != nil {
		in, out := &in.MaxRequest, &out.MaxRequest
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourcePolicy.
func (in *ContainerResourcePolicy) DeepCopy() *ContainerResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ContainerResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMFlags) DeepCopyInto(out *JVMFlags) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMFlags.
func (in *JVMFlags) DeepCopy() *JVMFlags {
	if in == nil {
		return nil
	}
	out := new(JVMFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMRecommendation) DeepCopyInto(out *JVMRecommendation) {
	*out = *in
	if in.CurrentFlags != nil {
		in, out := &in.CurrentFlags, &out.CurrentFlags
		*out = new(JVMFlags)
		**out = **in
	}
	if in.RecommendedFlags != nil {
		in, out := &in.RecommendedFlags, &out.RecommendedFlags
		*out = new(JVMFlags)
		**out = **in
	}
	if in.HeapUsedP99 != nil {
		in, out := &in.HeapUsedP99, &out.HeapUsedP99
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.NonHeapUsedP99 != nil {
		in, out := &in.NonHeapUsedP99, &out.NonHeapUsedP99
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.GCOverheadPercent != nil {
		in, out := &in.GCOverheadPercent, &out.GCOverheadPercent
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.PeakThreadCount != nil {
		in, out := &in.PeakThreadCount, &out.PeakThreadCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMRecommendation.
func (in *JVMRecommendation) DeepCopy() *JVMRecommendation {
	if in == nil {
		return nil
	}
	out := new(JVMRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaPolicy) DeepCopyInto(out *JavaPolicy) {
	*out = *in
	if in.GCOverheadWeight != nil {
		in, out := &in.GCOverheadWeight, &out.GCOverheadWeight
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaPolicy.
func (in *JavaPolicy) DeepCopy() *JavaPolicy {
	if in == nil {
		return nil
	}
	out := new(JavaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.MatchNames != nil {
		in, out := &in.MatchNames, &out.MatchNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeNames != nil {
		in, out := &in.ExcludeNames, &out.ExcludeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceValues) DeepCopyInto(out *ResourceValues) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceValues.
func (in *ResourceValues) DeepCopy() *ResourceValues {
	if in == nil {
		return nil
	}
	out := new(ResourceValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizePolicy) DeepCopyInto(out *RightsizePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizePolicy.
func (in *RightsizePolicy) DeepCopy() *RightsizePolicy {
	if in == nil {
		return nil
	}
	out := new(RightsizePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizePolicyList) DeepCopyInto(out *RightsizePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RightsizePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizePolicyList.
func (in *RightsizePolicyList) DeepCopy() *RightsizePolicyList {
	if in == nil {
		return nil
	}
	out := new(RightsizePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizePolicySpec) DeepCopyInto(out *RightsizePolicySpec) {
	*out = *in
	in.CommonPolicySpec.DeepCopyInto(&out.CommonPolicySpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizePolicySpec.
func (in *RightsizePolicySpec) DeepCopy() *RightsizePolicySpec {
	if in == nil {
		return nil
	}
	out := new(RightsizePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizePolicyStatus) DeepCopyInto(out *RightsizePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizePolicyStatus.
func (in *RightsizePolicyStatus) DeepCopy() *RightsizePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RightsizePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizeRecommendation) DeepCopyInto(out *RightsizeRecommendation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizeRecommendation.
func (in *RightsizeRecommendation) DeepCopy() *RightsizeRecommendation {
	if in == nil {
		return nil
	}
	out := new(RightsizeRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizeRecommendation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizeRecommendationList) DeepCopyInto(out *RightsizeRecommendationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RightsizeRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizeRecommendationList.
func (in *RightsizeRecommendationList) DeepCopy() *RightsizeRecommendationList {
	if in == nil {
		return nil
	}
	out := new(RightsizeRecommendationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RightsizeRecommendationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizeRecommendationSpec) DeepCopyInto(out *RightsizeRecommendationSpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	out.PolicyRef = in.PolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizeRecommendationSpec.
func (in *RightsizeRecommendationSpec) DeepCopy() *RightsizeRecommendationSpec {
	if in == nil {
		return nil
	}
	out := new(RightsizeRecommendationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RightsizeRecommendationStatus) DeepCopyInto(out *RightsizeRecommendationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Savings != nil {
		in, out := &in.Savings, &out.Savings
		*out = new(SavingsEstimate)
		**out = **in
	}
	if in.LastRecommendationTime != nil {
		in, out := &in.LastRecommendationTime, &out.LastRecommendationTime
		*out = (*in).DeepCopy()
	}
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
	if in.DataReadySince != nil {
		in, out := &in.DataReadySince, &out.DataReadySince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RightsizeRecommendationStatus.
func (in *RightsizeRecommendationStatus) DeepCopy() *RightsizeRecommendationStatus {
	if in == nil {
		return nil
	}
	out := new(RightsizeRecommendationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavingsEstimate) DeepCopyInto(out *SavingsEstimate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavingsEstimate.
func (in *SavingsEstimate) DeepCopy() *SavingsEstimate {
	if in == nil {
		return nil
	}
	out := new(SavingsEstimate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
