apiVersion: v2
name: cairn
description: JVM-aware Kubernetes resource rightsizing operator
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - kubernetes
  - rightsizing
  - vpa
  - java
  - jvm
  - cost-optimization
home: https://github.com/rebertim/cairn
sources:
  - https://github.com/rebertim/cairn
maintainers:
  - name: The Cairn Authors
    url: https://github.com/rebertim/cairn

dependencies:
  - name: kube-prometheus-stack
    version: "82.10.3"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-prometheus-stack.enabled
